### ISSUE TITLE
Thanks for your great work !  Please could you tell me the coefficients of T-Loss?

### ISSUE THREAD

**Issue by jhtobigs** [JinluZhang1126/MixSTE#3]
Hello, Thanks for your great work !
I'm trying to implementing and reproduce your work 'MixSTE' in tensorflow2.0
but I can't find the coefficients of T-Loss (MPJVE+TCLoss )in the paper
Please could you tell me the coefficients of T-Loss for reproducing?
(If I missed it, sorry for that)

**Comment by jhtobigs** [comment]
![image](https://user-images.githubusercontent.com/52998546/167364145-4eb3316e-442a-4bd4-9443-b5c761bf9a73.png)

**Comment by JinluZhang1126** [comment]
Hi, the coefficients are 0.5, and 1.0 respectively. 
Ps. If the MPJVE is very important for you, the coefficient of L_m can be set to 1.5 - 2.0 after convergence, and the coefficient of L_t can be set to 0.1. I do not do that because MPJVE is not the main metric.

Please let me know the performance of your implementation in TF2.0, I am kind of curious about that.😀
